print("Ingresa el valor de x1: ")
rX1 = float(input())
print("Ingresa el valor de y1: ")
rY1 = float(input())
print("Ingresa el valor de x2: ")
rX2 = float(input())
print("Ingresa el valor de y2: ")
rY2 = float(input())
rPendiente = (rY2 - rY1) / (rX2 - rX1)
print("El valor de la pendiente es: ", end='', flush=True)
print(rPendiente)
